#!/bin/bash -f
#**********************************************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Script generated by Vivado on Sun Jul 27 14:40:17 -03 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : system.sh
# Simulator    : Synopsys Verilog Compiler Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : system.sh
#                system.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                system.sh [-reset_run]
#                system.sh [-reset_log]
#                system.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'system.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set vhdlan compile options
vhdlan_opts="-full64 -l .tmp_log"

# set vlogan compile options
vlogan_opts="-full64 -l .tmp_log"

# set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc -t ps -licqueue -l elaborate.log"

# set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# set design libraries
design_libs=(xilinx_vip xpm xil_defaultlib axi_infrastructure_v1_1_0 axi_vip_v1_1_21 processing_system7_vip_v1_0_23 proc_sys_reset_v5_0_17 blk_mem_gen_v8_4_11 axi_bram_ctrl_v4_1_13 xlconstant_v1_1_10 smartconnect_v1_0 axi_register_slice_v2_1_35 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_5 axi_gpio_v2_0_37)

# simulation root library directory
sim_lib_dir="vcs_lib"

# script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2025.1 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./system.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > vlogan.log 2>/dev/null

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "/opt/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/opt/Xilinx/2025.1/Vivado/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xpm $vhdlan_opts \
  "/opt/Xilinx/2025.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_pll_0_0/system_pll_0_0_clk_wiz.v" \
  "../../../bd/system/ip/system_pll_0_0/system_pll_0_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_vip_v1_1_21 $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f16f/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work processing_system7_vip_v1_0_23 $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work proc_sys_reset_v5_0_17 $vhdlan_opts \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/9438/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/system/ip/system_rst_ps_0_50M_0/sim/system_rst_ps_0_50M_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_axis_adc_0_2/sim/system_axis_adc_0_2.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work blk_mem_gen_v8_4_11 $vlogan_opts +v2k +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a32c/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_blk_mem_gen_0_2/sim/system_blk_mem_gen_0_2.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work axi_bram_ctrl_v4_1_13 $vhdlan_opts \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/2f03/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/system/ip/system_axi_bram_ctrl_0_2/sim/system_axi_bram_ctrl_0_2.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_radar_sweep_ctrl_0_10/sim/system_radar_sweep_ctrl_0_10.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xlconstant_v1_1_10 $vlogan_opts +v2k +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a165/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_0/sim/bd_45a3_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_1/sim/bd_45a3_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_2/sim/bd_45a3_arsw_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_3/sim/bd_45a3_rsw_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_4/sim/bd_45a3_awsw_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_5/sim/bd_45a3_wsw_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_6/sim/bd_45a3_bsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/d800/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_7/sim/bd_45a3_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_8/sim/bd_45a3_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/dce3/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_9/sim/bd_45a3_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_10/sim/bd_45a3_s00a2s_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_11/sim/bd_45a3_sarn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_12/sim/bd_45a3_srn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_13/sim/bd_45a3_sawn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_14/sim/bd_45a3_swn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_15/sim/bd_45a3_sbn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_16/sim/bd_45a3_m00s2a_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_17/sim/bd_45a3_m00arn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_18/sim/bd_45a3_m00rn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_19/sim/bd_45a3_m00awn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_20/sim/bd_45a3_m00wn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_21/sim/bd_45a3_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/0133/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_22/sim/bd_45a3_m00e_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_23/sim/bd_45a3_m01s2a_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_24/sim/bd_45a3_m01arn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_25/sim/bd_45a3_m01rn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_26/sim/bd_45a3_m01awn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_27/sim/bd_45a3_m01wn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_28/sim/bd_45a3_m01bn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_29/sim/bd_45a3_m01e_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_30/sim/bd_45a3_m02s2a_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_31/sim/bd_45a3_m02arn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_32/sim/bd_45a3_m02rn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_33/sim/bd_45a3_m02awn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_34/sim/bd_45a3_m02wn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_35/sim/bd_45a3_m02bn_0.sv" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/ip/ip_36/sim/bd_45a3_m02e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_axi_smc_3/bd_0/sim/bd_45a3.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work axi_register_slice_v2_1_35 $vlogan_opts +v2k +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/c5b7/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/ip/system_axi_smc_3/sim/system_axi_smc_3.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work interrupt_control_v3_1_5 $vhdlan_opts \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/d8cc/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work axi_gpio_v2_0_37 $vhdlan_opts \
  "../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/0271/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vhdlan -work xil_defaultlib $vhdlan_opts \
  "../../../bd/system/ip/system_axi_gpio_0_0/sim/system_axi_gpio_0_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vhdlan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a9be" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/6cfa/hdl" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../utn_fmcw.gen/sources_1/bd/system/ipshared/a8e4/hdl/verilog" +incdir+"../../../../../../../../../opt/Xilinx/2025.1/data/rsb/busdef" +incdir+"/opt/Xilinx/2025.1/Vivado/data/xilinx_vip/include" \
  "../../../bd/system/sim/system.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> vlogan.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/bruno/git/utn-fmcw-radar/fpga_utn_fmcw/utn_fmcw.cache/compile_simlib/vcs"
  fi

  echo "LIBRARY_SCAN=TRUE" >> $file

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log lib_sc.so 64 AN.DB csrc system_simv.daidir vcs_lib c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(vlogan.log vhdlan.log compile.log elaborate.log simulate.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-step]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-reset_log]\n\
Usage: system.sh [-keep_index]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (compile, elaborate, simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
